"""empty message

Revision ID: 937a3d4d4ccf
Revises: 418fb5ef41dc
Create Date: 2016-10-23 18:09:00.145051

"""

# revision identifiers, used by Alembic.
revision = '937a3d4d4ccf'
down_revision = '418fb5ef41dc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'rate')
    op.add_column('managers', sa.Column('rate', sa.Float(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('managers', 'rate')
    op.add_column('agents', sa.Column('rate', mysql.FLOAT(), nullable=False))
    ### end Alembic commands ###
